/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fotunatoformule;

/**
 *
 * @author egliocz
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Calcolator c = new Calcolator();
        Risultato res = c.calcola();
        System.out.println("PRIMA FORMULA===================================");
        for (int i = 0; i < res.getLamds().length; i++) {
            System.out.println("risultato numero " + (i + 1));
            System.out.println("λ = " + res.lamds[i] + " Q = " + res.qq[i]);
        }
        System.out.println("==================================================\n\nSECONDA FORMULA===================================");
        cALCOLATOR2 c2 = new cALCOLATOR2();
        Risultato res2 = c2.calcola();
        for (int i = 0; i < res2.getLamds().length; i++) {
            System.out.println("risultato numero " + (i + 1));
            System.out.println("λ = " + res2.lamds[i] + " J = " + res2.qq[i]);
        }
        System.out.println("==================================================\n\nTERZA FORMULA=====================================");
        calculator3 c3 = new calculator3();
        Risultato res3 = c3.calcola();
        for (int i = 0; i < res2.getLamds().length; i++) {
            System.out.println("risultato numero " + (i + 1));
            System.out.println("λ = " + res3.lamds[i] + " D = " + res3.qq[i]);
        }
        
        System.exit(0);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
