/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unisa.oop2013.contest4.gruppo11;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author gruppo11
 */
public class StudentHouseGUI extends javax.swing.JFrame {

    GestioneCamere gc = new GestioneCamere();

    /**
     * Creates new form StudentHouseGUI
     */
    public StudentHouseGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuovoButton = new javax.swing.JButton();
        caricaButton = new javax.swing.JButton();
        salvaButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cameraLabel = new javax.swing.JLabel();
        studenteLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        pianoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        cognomeLabel = new javax.swing.JLabel();
        nazionalitàLabel = new javax.swing.JLabel();
        numeroField = new javax.swing.JTextField();
        pianoField = new javax.swing.JTextField();
        nomeField = new javax.swing.JTextField();
        cognomeField = new javax.swing.JTextField();
        nazionalitàField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        separator = new javax.swing.JSeparator();
        affittoLabel = new javax.swing.JLabel();
        aggiungiButton = new javax.swing.JButton();
        eliminaButton = new javax.swing.JButton();
        affittoMensileField = new javax.swing.JTextField();
        calcolaTotaleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuovoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nuovoButton.setText("Nuovo");
        nuovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovoButtonActionPerformed(evt);
            }
        });

        caricaButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        caricaButton.setText("Carica");
        caricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaButtonActionPerformed(evt);
            }
        });

        salvaButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salvaButton.setText("Salva");
        salvaButton.setEnabled(false);
        salvaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaButtonActionPerformed(evt);
            }
        });

        cameraLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cameraLabel.setText("Camera");

        studenteLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studenteLabel.setText("Studente");

        numeroLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroLabel.setText("Numero");

        pianoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pianoLabel.setText("Piano");

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setText("Nome");

        cognomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cognomeLabel.setText("Cognome");

        nazionalitàLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nazionalitàLabel.setText("Nazionalità");

        numeroField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroField.setEnabled(false);

        pianoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pianoField.setEnabled(false);

        nomeField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeField.setEnabled(false);

        cognomeField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cognomeField.setEnabled(false);

        nazionalitàField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nazionalitàField.setEnabled(false);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textArea.setRows(5);
        textArea.setEnabled(false);
        jScrollPane1.setViewportView(textArea);

        separator.setOpaque(true);

        affittoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        affittoLabel.setText("Affitto Mensile");

        aggiungiButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aggiungiButton.setText("Aggiungi");
        aggiungiButton.setEnabled(false);
        aggiungiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiButtonActionPerformed(evt);
            }
        });

        eliminaButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eliminaButton.setText("Elimina");
        eliminaButton.setEnabled(false);
        eliminaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaButtonActionPerformed(evt);
            }
        });

        affittoMensileField.setEditable(false);
        affittoMensileField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        affittoMensileField.setEnabled(false);

        calcolaTotaleButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calcolaTotaleButton.setText("Calcola totale");
        calcolaTotaleButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separator)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroLabel)
                                    .addComponent(pianoLabel))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cameraLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numeroField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(pianoField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeLabel)
                                            .addComponent(cognomeLabel)
                                            .addComponent(nazionalitàLabel))
                                        .addGap(23, 23, 23)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studenteLabel)
                                    .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(cognomeField)
                                    .addComponent(nazionalitàField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nuovoButton)
                                .addGap(18, 18, 18)
                                .addComponent(caricaButton)
                                .addGap(18, 18, 18)
                                .addComponent(salvaButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(aggiungiButton)
                                .addGap(18, 18, 18)
                                .addComponent(eliminaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(affittoLabel)
                                .addGap(38, 38, 38)
                                .addComponent(affittoMensileField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calcolaTotaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuovoButton)
                            .addComponent(caricaButton)
                            .addComponent(salvaButton))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cameraLabel)
                            .addComponent(studenteLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroLabel)
                            .addComponent(nomeLabel)
                            .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pianoLabel)
                            .addComponent(cognomeLabel)
                            .addComponent(cognomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pianoField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazionalitàLabel)
                    .addComponent(nazionalitàField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aggiungiButton)
                    .addComponent(eliminaButton))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affittoMensileField)
                    .addComponent(calcolaTotaleButton)
                    .addComponent(affittoLabel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nuovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovoButtonActionPerformed
        
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                nuovoButton.setEnabled(false);
                caricaButton.setEnabled(false);
                salvaButton.setEnabled(true);
                numeroField.setEnabled(true);
                pianoField.setEnabled(true);
                nomeField.setEnabled(true);
                cognomeField.setEnabled(true);
                nazionalitàField.setEnabled(true);
                aggiungiButton.setEnabled(true);
                eliminaButton.setEnabled(true);
                textArea.setEnabled(true);
                affittoMensileField.setEnabled(true);
                calcolaTotaleButton.setEnabled(true);
            }
        });

    }//GEN-LAST:event_nuovoButtonActionPerformed

    private void caricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricaButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int scelta = chooser.showOpenDialog(this);
        if (scelta == JFileChooser.APPROVE_OPTION) //controlla se è stato scelto di aprire il file  
        {
            File scelto = chooser.getSelectedFile();
            gc.leggiFile(scelto);

        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                nuovoButton.setEnabled(false);
                caricaButton.setEnabled(false);
                salvaButton.setEnabled(true);
                numeroField.setEnabled(true);
                pianoField.setEnabled(true);
                nomeField.setEnabled(true);
                cognomeField.setEnabled(true);
                nazionalitàField.setEnabled(true);
                aggiungiButton.setEnabled(true);
                eliminaButton.setEnabled(true);
                textArea.setEnabled(true);
                affittoMensileField.setEnabled(true);
                calcolaTotaleButton.setEnabled(true);
                textArea.setText(gc.toString());
            }
        });

        // TODO add your handling code here:
    }//GEN-LAST:event_caricaButtonActionPerformed

    private void salvaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int scelta = chooser.showSaveDialog(this);
        if (scelta == JFileChooser.APPROVE_OPTION) // controlla se l'utente ha confermato
        {
            File scelto = chooser.getSelectedFile();
            gc.salvaFile(scelto);
        }
    }//GEN-LAST:event_salvaButtonActionPerformed

    private void aggiungiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiButtonActionPerformed
        if (nomeField.getText().compareTo("") == 0
                || cognomeField.getText().compareTo("") == 0
                || nazionalitàField.getText().compareTo("") == 0
                || numeroField.getText().compareTo("") == 0
                || pianoField.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Dati incompleti", "ATTENZIONE", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Camera c = new Camera(Integer.parseInt(numeroField.getText()), Integer.parseInt(pianoField.getText()));
                Studente s = new Studente(nomeField.getText(), cognomeField.getText(), nazionalitàField.getText());
                gc.assegnaCamera(c, s);
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        textArea.setText(gc.toString());
                    }
                });
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Devi inserire un numero!", "ATTENZIONE!", JOptionPane.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_aggiungiButtonActionPerformed

    private void eliminaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaButtonActionPerformed
        try {
            int numero = Integer.parseInt(numeroField.getText());
            gc.rimuoviCamera(numero);
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    textArea.setText(gc.toString());
                }
            });
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Devi inserire un numero!", "ATTENZIONE!", JOptionPane.WARNING_MESSAGE);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_eliminaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHouseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHouseGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affittoLabel;
    private javax.swing.JTextField affittoMensileField;
    private javax.swing.JButton aggiungiButton;
    private javax.swing.JButton calcolaTotaleButton;
    private javax.swing.JLabel cameraLabel;
    private javax.swing.JButton caricaButton;
    private javax.swing.JTextField cognomeField;
    private javax.swing.JLabel cognomeLabel;
    private javax.swing.JButton eliminaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nazionalitàField;
    private javax.swing.JLabel nazionalitàLabel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField numeroField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JButton nuovoButton;
    private javax.swing.JTextField pianoField;
    private javax.swing.JLabel pianoLabel;
    private javax.swing.JButton salvaButton;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel studenteLabel;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
